@SwiftLink.Presentation_HostAddress = http://localhost:56459

GET {{SwiftLink.Presentation_HostAddress}}/Health
Accept: application/json
###

POST {{SwiftLink.Presentation_HostAddress}}/api/v1.0/link/Shorten
Content-Type: application/json

{
    "Url": "https://agah.com",
    "Description": "Description",
    "Password": "Pass@123",
}
###

POST {{SwiftLink.Presentation_HostAddress}}/api/v1.0/subscriber/Add
Content-Type: application/json

{
    "email": "m.karimi@gmail.com",
    "name": "Mohammad Karimi"
}
###

GET {{SwiftLink.Presentation_HostAddress}}/api/v1.0/link/Count
